# Generated by Django 2.0.5 on 2018-05-11 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('paye', models.BooleanField()),
                ('validetermine', models.BooleanField()),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('datefineffective', models.DateField()),
                ('longueur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('marquageroute', models.BooleanField()),
                ('espacevert', models.BooleanField()),
                ('factureentreprise', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('npa', models.IntegerField()),
                ('lieu', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PermisFouille',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('hkoord', models.FloatField()),
                ('vkoord', models.FloatField()),
                ('archeologique', models.IntegerField()),
                ('archeologique_existant', models.IntegerField()),
                ('rue_ref', models.IntegerField()),
                ('ruenum_ref', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpf.Demande')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('archeologue', models.BooleanField()),
                ('texteemail', models.TextField()),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('valideur', models.BooleanField()),
                ('administrateur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeEmplacement',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('effectue', models.BooleanField()),
                ('accepte', models.BooleanField()),
                ('remarque', models.TextField()),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpf.Demande')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpf.Service')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_entreprise', to='gpf.Intervenant'),
        ),
        migrations.AddField(
            model_name='demande',
            name='maitreouvrage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_maitreouvrage', to='gpf.Intervenant'),
        ),
        migrations.AddField(
            model_name='demande',
            name='typeemplacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpf.TypeEmplacement'),
        ),
    ]
