# Generated by Django 2.0.5 on 2018-05-23 09:04

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('person_in_charge', models.CharField(max_length=100)),
                ('phone_fixed', models.IntegerField()),
                ('phone_mobile', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_content', models.TextField()),
                ('is_validator', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('is_archeologist', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField()),
                ('validated', models.BooleanField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('date_effective_end', models.DateField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('has_road_marking', models.BooleanField()),
                ('is_green_area', models.BooleanField()),
                ('invoiced', models.BooleanField()),
                ('description', models.TextField()),
                ('has_archeology', models.BooleanField()),
                ('has_existing_archeology', models.BooleanField()),
                ('road_ref', models.IntegerField()),
                ('road_number_ref', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permitrequest_company', to='gpf.Actor')),
                ('project_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permitrequest_project_owner', to='gpf.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('comment', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpf.Department')),
                ('permitrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpf.PermitRequest')),
            ],
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='sitetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpf.SiteType'),
        ),
    ]
