# Generated by Django 2.0.5 on 2018-05-29 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='fax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='person_in_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='phone_fixed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='phone_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='email_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='date_effective_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=2056),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='road_number_ref',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='road_ref',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
