# Generated by Django 2.0.5 on 2018-05-08 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisFouille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('hkoord', models.FloatField()),
                ('vkoord', models.FloatField()),
                ('archeologique', models.IntegerField()),
                ('archeologique_existant', models.IntegerField()),
                ('rue_ref', models.IntegerField()),
                ('ruenum_ref', models.IntegerField()),
                ('demande_ref', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=2056)),
            ],
        ),
    ]
