# Generated by Django 2.0.5 on 2018-05-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('gpf', '0002_auto_20180529_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gpf.Actor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            bases=('gpf.actor',),
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gpf.Actor')),
            ],
            bases=('gpf.actor',),
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='email_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
