# Generated by Django 2.0.5 on 2018-06-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0003_archelogy'),
        ('gpf', '0006_auto_20180531_1637'),
    ]

    operations = [
    ]
