# Generated by Django 2.0.5 on 2018-06-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0008_commenttemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permitrequest',
            old_name='has_road_marking',
            new_name='road_marking_damaged',
        ),
    ]
