# Generated by Django 2.0.5 on 2018-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0009_auto_20180601_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='invoiced',
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='invoice_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
