# Generated by Django 2.0.5 on 2018-06-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0011_creditortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='invoice_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpf.CreditorType'),
        ),
    ]
