# Generated by Django 2.0.5 on 2018-06-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0012_auto_20180601_0951'),
        ('gpf', '0007_merge_20180601_0730'),
    ]

    operations = [
    ]
