# Generated by Django 2.0.5 on 2018-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0013_merge_20180601_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
