# Generated by Django 2.0.5 on 2018-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0014_auto_20180601_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='has_archeology',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='has_existing_archeology',
            field=models.BooleanField(default=False),
        ),
    ]
