# Generated by Django 2.0.5 on 2018-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpf', '0015_auto_20180601_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
